service: my-serverless-api
frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    SUPABASE_URL: ${env:SUPABASE_URL}
    SUPABASE_KEY: ${env:SUPABASE_KEY}

plugins:
  - serverless-offline

functions:
  createClient:
    handler: src/infrastructure/lambdas/handler.handler
    events:
      - http:
          path: /clients
          method: post
          cors: true

custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: true
    target: "node18"
    platform: "node"
    exclude: ['aws-sdk']
    packager: "npm"

package:
  include:
    - node_modules/**
  exclude:
    - node_modules/aws-sdk/**